version: '3'

services:
  db:
    container_name: HotelDB-Dev
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - ./mongo:/data/db